export const EMAIL_AUTH_SIGNUP_REQUEST = "EMAIL_AUTH_2/SIGNUP/REQUEST";
export const EMAIL_AUTH_SIGNUP_SUCCESS = "EMAIL_AUTH_2/SIGNUP/SUCCESS";
export const EMAIL_AUTH_SIGNUP_ERROR = "EMAIL_AUTH_2/SIGNUP/ERROR";

export const EMAIL_AUTH_LOGIN_REQUEST = "EMAIL_AUTH_2/LOGIN/REQUEST";
export const EMAIL_AUTH_LOGIN_SUCCESS = "EMAIL_AUTH_2/LOGIN/SUCCESS";
export const EMAIL_AUTH_LOGIN_ERROR = "EMAIL_AUTH_2/LOGIN/ERROR";

// does not follow the patern REQUERST/SUCCESS/ERROR since it is syncronus action
export const EMAIL_AUTH_LOGOUT = "EMAIL_AUTH_2/LOGOUT";

export const EMAIL_AUTH_PASSWORD_RECOVER_REQUEST =
  "EMAIL_AUTH_2/PASSWORD_RECOVER/REQUEST";
export const EMAIL_AUTH_PASSWORD_RECOVER_SUCCESS =
  "EMAIL_AUTH_2/PASSWORD_RECOVER/SUCCESS";
export const EMAIL_AUTH_PASSWORD_RECOVER_ERROR =
  "EMAIL_AUTH_2/PASSWORD_RECOVER/ERROR";